id = "aozorabunko-lsp-by-aozora-rs"
name = "Aozorabunko"
version = "0.0.1"
schema_version = 1
authors = ["Kinokov"]
description = "An Aozorabunko markup's LSP, powered by aozora.rs"
repository = "https://github.com/kinoko0518/aozora-rs"

[language_servers.aozora-rs]
name = "aozora-rs"
languages = ["aozora"]
